# Python 3.15 defers these imports; older runtimes ignore the declaration.
__lazy_modules__ = frozenset(
    {
        "padwan_ai._base",
        "padwan_ai._deprecation",
        "padwan_ai.agent",
        "padwan_ai.anthropic",
        "padwan_ai.audio",
        "padwan_ai.client",
        "padwan_ai.content",
        "padwan_ai.conversation",
        "padwan_ai.errors",
        "padwan_ai.gemini",
        "padwan_ai.grok",
        "padwan_ai.mcp",
        "padwan_ai.mistral",
        "padwan_ai.models",
        "padwan_ai.openai",
        "padwan_ai.typesafe",
        "padwan_ai.vision",
    }
)

from importlib.metadata import version as _pkg_version

from ._base import ChatStream, LLMClientBase, OnThought, RealtimeClientBase
from ._deprecation import ModelDeprecationWarning
from .agent import (
    AgentOutput,
    AgentSession,
    ConversationStore,
    OnMcpConnect,
    ToolCallContext,
)
from .anthropic import (
    ANTHROPIC_MODELS,
    AnthropicClient,
    AnthropicModel,
    is_anthropic_model,
)
from .audio import supports_audio
from .client import LLMClient, RealtimeClient
from .content import (
    AudioFormat,
    ContentAudioPart,
    ContentImagePart,
    ContentPart,
    ContentTextPart,
    audio_part,
    content_parts,
    image_part,
    text_file_part,
    text_part,
)
from .conversation import (
    AssistantToolMessage,
    ChatMessage,
    ConversationSnapshot,
    ConversationState,
    Message,
    ToolResultMessage,
)
from .errors import LLMError, OutputError, Provider
from .gemini import (
    GEMINI_MODELS,
    GeminiClient,
    GeminiModel,
    GeminiRealtimeClient,
    GeminiRealtimeConnection,
    is_gemini_model,
)
from .grok import GROK_MODELS, GrokClient, GrokModel, GrokRealtimeClient, is_grok_model
from .mcp import McpStdio, McpStreamable, McpTool, McpTransport, OnAuth, ProgressEvent
from .mistral import MISTRAL_MODELS, MistralClient, MistralModel, is_mistral_model
from .models import (
    ChatResponse,
    FinishReason,
    ToolCall,
    ToolCallFunction,
    ToolDefinition,
    UsageToken,
)
from .openai import (
    OPENAI_CHAT_MODELS,
    OPENAI_MODELS,
    OpenAIClient,
    OpenAIModel,
    OpenAIRealtimeClient,
    RealtimeConnection,
    RealtimeServerEvent,
    is_openai_model,
)
from .typesafe import (
    TYPESAFE_MODELS,
    ChoiceAnswer,
    ChoiceQuestion,
    NoulAnswer,
    NoulCriteria,
    NoulQuestion,
    ScoreAnswer,
    ScoreQuestion,
    SystemOneResponse,
    TypeSafeClient,
    TypeSafeModel,
    TypeSafeUsage,
)
from .vision import supports_vision

__all__ = (
    "ANTHROPIC_MODELS",
    "GEMINI_MODELS",
    "GROK_MODELS",
    "MISTRAL_MODELS",
    "OPENAI_CHAT_MODELS",
    "OPENAI_MODELS",
    "TYPESAFE_MODELS",
    "AgentOutput",
    "AgentSession",
    "AnthropicClient",
    "AnthropicModel",
    "AssistantToolMessage",
    "AudioFormat",
    "ChatMessage",
    "ChatResponse",
    "ChatStream",
    "ChoiceAnswer",
    "ChoiceQuestion",
    "ContentAudioPart",
    "ContentImagePart",
    "ContentPart",
    "ContentTextPart",
    "ConversationSnapshot",
    "ConversationState",
    "ConversationStore",
    "FinishReason",
    "GeminiClient",
    "GeminiModel",
    "GeminiRealtimeClient",
    "GeminiRealtimeConnection",
    "GrokClient",
    "GrokModel",
    "GrokRealtimeClient",
    "LLMClient",
    "LLMClientBase",
    "LLMError",
    "McpStdio",
    "McpStreamable",
    "McpTool",
    "McpTransport",
    "Message",
    "MistralClient",
    "MistralModel",
    "ModelDeprecationWarning",
    "OnAuth",
    "OnMcpConnect",
    "OnThought",
    "OpenAIClient",
    "OpenAIModel",
    "OpenAIRealtimeClient",
    "NoulAnswer",
    "NoulCriteria",
    "NoulQuestion",
    "OutputError",
    "ProgressEvent",
    "Provider",
    "RealtimeClient",
    "RealtimeClientBase",
    "RealtimeConnection",
    "RealtimeServerEvent",
    "ScoreAnswer",
    "ScoreQuestion",
    "SystemOneResponse",
    "ToolCall",
    "ToolCallContext",
    "ToolCallFunction",
    "ToolDefinition",
    "ToolResultMessage",
    "TypeSafeClient",
    "TypeSafeModel",
    "TypeSafeUsage",
    "UsageToken",
    "__version__",
    "audio_part",
    "content_parts",
    "image_part",
    "is_anthropic_model",
    "is_gemini_model",
    "is_grok_model",
    "is_mistral_model",
    "is_openai_model",
    "supports_audio",
    "supports_vision",
    "text_file_part",
    "text_part",
)

__version__: str = _pkg_version("padwan-ai")
